### ISSUE TITLE
[Interactive Book] Fix Images not loading in pages.

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/mobile-app#102]
**Describe the bug**
Current version of Interactive Book doesn't supports *SVG* images and HTML image tags.

**ToDo**
- [ ] https://github.com/CircuitVerse/Interactive-Book/issues/558
- [x] #113

**NOTE: Interactive Book being in beta, can be checked in `ib` branch**

**Comment by ShreyaPrasad1209** [comment]
@manjotsidhu can we add this to good first issues?

**Comment by vvijayalakshmi21** [comment]
Hello.
I am interested to pick this up

**Comment by manjotsidhu** [comment]
> Hello.
> I am interested to pick this up

Good to hear that, you can start with the first ToDo item https://github.com/CircuitVerse/Interactive-Book/issues/558
