### ISSUE TITLE
[Interactive Book] Fix inline HTML tags like sup and sub

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/mobile-app#103]
**Describe the bug**
We need to support important inline HTML tags like **subscript** and **superscript**

**ToDo**
- [ ] Custom Inline Syntax for subscript and superscript.
- [ ] Custom subscript and superscript Text Builder.

Reference: https://github.com/flutter/packages/blob/master/packages/flutter_markdown/example/lib/demos/subscript_syntax_demo.dart

**NOTE: Interactive Book being in beta, can be checked in `ib` branch**

**Comment by ShreyaPrasad1209** [comment]
@manjotsidhu we can add this to good first issues right?
