### ISSUE TITLE
[Interactive Book] Showcase and brief buttons and toggles at first launch.

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/mobile-app#105]
**Is your feature request related to a problem? Please describe.**
Someone new to Interactive Book will find all the options like Table of Contents, Chapters and Sections confusing, we should provide an introductory briefing about Interactive Book and it's options.

**Describe the solution you'd like**
Showcasing the App at first launch using Flutter package would be ideal, this will involve designing the Showcase wrapper widget on top of our built-in widgets.

**Additional context**
![image](https://user-images.githubusercontent.com/22657113/124296890-16cca180-db78-11eb-9a49-458783679a1e.png)

https://pub.dev/packages/showcaseview

**Comment by roopak99** [comment]
can i work on this issue?

**Comment by manjotsidhu** [comment]
> can i work on this issue?

Sure, go ahead.

**Comment by Samdid** [comment]
I would like to work on this issue, @manjotsidhu can you assign it to me?

**Comment by manjotsidhu** [comment]
> I would like to work on this issue, @manjotsidhu can you assign it to me? 

Go ahead!

**Comment by Samdid** [comment]
Hey @manjotsidhu, on which screen do I have to add this feature?

**Comment by manjotsidhu** [comment]
> Hey @manjotsidhu, on which screen do I have to add this feature?

Interactive Book Home

**Comment by Samdid** [comment]
Okay!!

**Comment by aman-singh7** [comment]
Hey @manjotsidhu , can I work on this?
