### ISSUE TITLE
[Null Safety] swap `flutter_icons` with `fluttericon`

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/mobile-app#119]
Since `flutter_icons` doesn't supports null-safety, we need to swap it with `fluttericon` to make sure our dependencies are sound null-safe in accordance with Dart 2.0

https://pub.dev/packages/fluttericon

**Comment by santoshdvc** [comment]
@manjotsidhu I see there is no `fluttericon.dart` file in the dependency `fluttericon`. It needs to be replaced with some other icon pack from the dependency.

**Comment by manjotsidhu** [comment]
> @manjotsidhu I see there is no `fluttericon.dart` file in the dependency `fluttericon`. It needs to be replaced with some other icon pack from the dependency.

You have to change implementation also, the same icons are present in `fluttericon` but it's usage will be different.

**Comment by santoshdvc** [comment]
Okay. I will see to it.
