### ISSUE TITLE
[BUG] ERROR: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.

### ISSUE THREAD

**Issue by roopak99** [CircuitVerse/mobile-app#138]
**Describe the bug**
After updating `Flutter (Channel stable, 2.5.0)` to the latest versions, I'm getting the following error when building:

/../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type '`PointerEvent`' can't be assigned to the parameter type '`PointerDownEvent`'.

    '`PointerEvent`' is from 'package:flutter/src/gestures/events.dart' ('/../flutter/packages/flutter/lib/src/gestures/events.dart').
    '`PointerDownEvent`' is from 'package:flutter/src/gestures/events.dart' ('/../flutter/packages/flutter/lib/src/gestures/events.dart'). super.addAllowedPointer(event);

**Device Information [optional]:** Android

**Additional context**

Error Caused due to the plugin : `photo_view: 0.11.1 `

**Are you working on this issue? (Yes/No)** No

**Comment by manjotsidhu** [comment]
> **Describe the bug**
> After updating `Flutter (Channel stable, 2.5.0)` to the latest versions, I'm getting the following error when building:
> 
> /../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type '`PointerEvent`' can't be assigned to the parameter type '`PointerDownEvent`'.
> 
> ```
> '`PointerEvent`' is from 'package:flutter/src/gestures/events.dart' ('/../flutter/packages/flutter/lib/src/gestures/events.dart').
> '`PointerDownEvent`' is from 'package:flutter/src/gestures/events.dart' ('/../flutter/packages/flutter/lib/src/gestures/events.dart'). super.addAllowedPointer(event);
> ```
> 
> **Device Information [optional]:** Android
> 
> **Additional context**
> 
> Error Caused due to the plugin : `photo_view: 0.11.1 `
> 
> **Are you working on this issue? (Yes/No)** No

The latest version of photo_view is `0.12.0`. You can try updating to that, it should fix that issue

**Comment by manjotsidhu** [comment]
This is a breaking issue in Flutter 2.5. 
https://github.com/bluefireteam/photo_view/issues/459
Either wait for this [PR](https://github.com/bluefireteam/photo_view/pull/462) to get merged or use [forked photo_view](https://github.com/bluefireteam/photo_view/issues/459#issuecomment-918020139) with flutter 2.5 support

**Comment by roopak99** [comment]
[This](https://github.com/bluefireteam/photo_view/issues/459#issuecomment-918020139) solved this issue temporarily

**Comment by renancaraujo** [comment]
This was fixed on photoview 0.12.0.

**Comment by renancaraujo** [comment]
https://github.com/bluefireteam/photo_view/issues/459#issuecomment-921678753
