### ISSUE TITLE
Hacktoberfest Recommendations

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/mobile-app#139]
Hacktoberfest 2021 is coming on 1st October, we should apply the recommendations given by Hacktoberfest -

- [x] Add the 'hacktoberfest' topic to your repository/project so that folks know you're participating in Hacktoberfest.
- [x] Apply the 'Hacktoberfest' label to issues in your GitHub or GitLab project that are ready for contributors to work on.
- [ ] Add a CONTRIBUTING.md file with contribution guidelines to your repository.
- [x] Choose issues that have a well-defined scope and are self-contained.
- [x] Adopt a code of conduct to foster a greater sense of inclusion and community.

Ref: https://hacktoberfest.digitalocean.com/resources/maintainers

**Comment by rktejesh** [comment]
Can I work on this issue @manjotsidhu
