### ISSUE TITLE
Need upgradation to V2 Embedding 

### ISSUE THREAD

**Issue by RohanSengupta326** [CircuitVerse/mobile-app#164]
**Is your feature request related to a problem? Please describe.**
The plugin `flutter_web_auth` uses a deprecated version of the Android embedding.

**Describe the solution you'd like**
Migrating to V2 embedding. 

**Are you working on this? (Yes/No)**
No

**Comment by manjotsidhu** [comment]
This is due to the package `flutter_web_auth` and not caused by our mobile app. I will keep this opened, if there is a newer version of this package available then that might fix this issue.

**Comment by aman-singh7** [comment]
@manjotsidhu  This is already fixed in #201
