### ISSUE TITLE
Disable add button on empty input field of Add Group Members

### ISSUE THREAD

**Issue by Sparsh1212** [CircuitVerse/mobile-app#17]
**Is your feature request related to a problem? Please describe.**
If the input field is left blank and user presses the ADD button then it shows a **_**Enter emails in valid format**_** error message.

![image](https://user-images.githubusercontent.com/55937724/98930836-3472cb00-2503-11eb-9b45-3070cd752147.png)

This error message is not appropriate, since the user hasn't entered any email yet, so there comes no question of correct email format. 
**Describe the solution you'd like**
It will be better to disable the ADD button till the input field is empty. This will result into a better UX.

Are you working on this? (Yes/No)
No

**Comment by cyber-venom003** [comment]
@Sparsh1212 @satu0king I would like to work on this. Can you please assign it to me?
