### ISSUE TITLE
Spelling error in image picker bottom sheet

### ISSUE THREAD

**Issue by Sparsh1212** [CircuitVerse/mobile-app#19]
**Is your feature request related to a problem? Please describe.**
There is typo in the spelling of **Gallery** in the bottom sheet of image picker.

![image](https://user-images.githubusercontent.com/55937724/98944164-a43e8100-2516-11eb-9c01-12780935cf38.png)

Describe the solution you'd like

**_Option1:_** Make changes in the implementation of the package and then use the modified package.
**_Option2:_** Use an alternative package.

**Are you working on this? (Yes/No)**
Yes

**Comment by manjotsidhu** [comment]
@Sparsh1212 I have submitted a Pull Request for the change to the `html_editor` library. You can find it [here](https://github.com/xrb21/flutter-html-editor/pull/26). This issue will get fixed once the PR gets merged.

**Comment by manjotsidhu** [comment]
@Nitish145 the new version of it is not released in `pub.dev` and the issue still persists. when version `1.0.2` will be available then only this will get fixed.

**Comment by ZadeAbhishek** [comment]
![Screenshot_1607925820](https://user-images.githubusercontent.com/66520848/102045987-57451780-3e00-11eb-89e6-9cabbc82c66f.png)

i have corrected it please check

**Comment by manjotsidhu** [comment]
> ![Screenshot_1607925820](https://user-images.githubusercontent.com/66520848/102045987-57451780-3e00-11eb-89e6-9cabbc82c66f.png)
> untill new version come can we keep like this ?? @manjotsidhu

The new version should have the same changes.

**Comment by ZadeAbhishek** [comment]
yep !
