### ISSUE TITLE
CountryInstituteAPI is not fetching country and institute data on edit profile page.

### ISSUE THREAD

**Issue by noman2002** [CircuitVerse/mobile-app#212]
**Describe the bug**
CountryInstituteAPI is not fetching country data on the edit profile page.

**To Reproduce**

1. Go to 'Profile page'
2. Click on 'edit profile'
3. Entry country name

**Expected behavior**
It should load a list of counties.

**Screenshots**
<img src="https://user-images.githubusercontent.com/54404474/158068274-5f4d860d-700c-4c09-9c99-43b17c5205ba.png" height="600" width="300"/>

**Are you working on this issue? (Yes/No)**
**Yes**

**Comment by manjotsidhu** [comment]
@aman-singh7 @ItsAdityaKSingh Are you guys able to reproduce this Issue ?
