### ISSUE TITLE
Add timeout to github actions

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/mobile-app#215]
Sometimes build action take hours due to external dependencies, setup timeout to handle those scenarios.
Ref: https://markfontenot.net/2021/09/21/adding-timeout-to-github-actions/#:~:text=To%20add%20a%20timeout%20to,repo%20after%20confirming%20the%20addition.

**Comment by SarveshLimaye** [comment]
@tachyons would like to work on this issue . Can you also let me know the timeout period for the actions to run 😄

**Comment by tachyons** [comment]
We need to figure that using based on the existing successful jobs
