### ISSUE TITLE
CVFlatButton active color does not change in dialog

### ISSUE THREAD

**Issue by aman-singh7** [CircuitVerse/mobile-app#233]
**Describe the bug**
The button state does not change from inactive to active when the text field has text.

**To Reproduce**

1. Go to any Owned Group
2. Click on 'Add' on the right of Mentors/Members
3. Edit the email text field
4. See the error

**Expected behavior**
The flat button color should be green when the text field is not empty.

**Screenshots

https://user-images.githubusercontent.com/77198905/178121337-5d8e9d43-b2f6-4e81-8623-ffb80f33e9f4.mp4

**Are you working on this issue? (Yes/No)**

**Comment by Aditya-150** [comment]
Hey @aman-singh7, can I work on this?

**Comment by Aditya-150** [comment]
@manjotsidhu can you please review the pull request.
