### ISSUE TITLE
Automatically create chips for email

### ISSUE THREAD

**Issue by aman-singh7** [CircuitVerse/mobile-app#241]
**Is your feature request related to a problem? Please describe.**
While adding members or mentors to the group, we have to input emails separated by coma(,) to make it more visual, we can show chips for each email.

**Describe the solution you'd like**
For context you can see this package **flutter_chip_input**.

**Are you working on this? (Yes/No)**

**Comment by razaAtif** [comment]
Hi @aman-singh7 I would like to contribute on this issue, can you please assign this issue to me.

**Comment by anuragrao04** [comment]
@aman-singh7

**Comment by aman-singh7** [comment]
@anuragrao04, you can start working if someone doesn't show any update on the assigned issue in a week. He will be unassigned.

**Comment by anuragrao04** [comment]
Thanks! can you please assign me this issue on the 19th of this month? I will have my exam week from the 14th to the 18th of November. I would still try to work on the issue during this period though. If anybody wants to work on the issue during this period, they can be assigned and I will not be blocking the issue. I will ping back here on the 19th as a reminder :)

**Comment by danger-ahead** [comment]
I am working on this issue.

**Comment by danger-ahead** [comment]
@aman-singh7 can you please checkout the latest pr?
