### ISSUE TITLE
flutter pub get doesn't work and gets stuck

### ISSUE THREAD

**Issue by danger-ahead** [CircuitVerse/mobile-app#243]
**Describe the bug**
`flutter pub get` doesn't work.

**To Reproduce**

1. Run `flutter pub get` after cloning the repo.
```bash
Warning: You are using these overridden dependencies:
! markdown 6.0.0 from git https://github.com/dart-lang/markdown.git at 32a945
! mime 1.0.2
! plugin_platform_interface 2.1.2 (2.1.3 available)
```
`flutter pub get` gets stuck.

**Expected behavior**
Running `flutter pub get` should have downloaded the dependencies.

**Are you working on this issue? (Yes/No)** Willing to work on this issue.

**Comment by aman-singh7** [comment]
I am not able to reproduce this. Please check your internet connectivity.
