### ISSUE TITLE
Update State Management of Interative Book

### ISSUE THREAD

**Issue by Tanmoy741127** [CircuitVerse/mobile-app#251]
**Is your feature request related to a problem? Please describe.**
In the Interactive book, if we scroll, the scroll controller listener functions are rebuilding the whole screen. That is causing lagginess in the app. As an effect, 
- the embedded quiz gets reset every time when we scroll
- some embedded components like Circuit Preview, and Images get reloaded every time the scroll position changes.
- It slows down the app and consumes much higher ram and network bandwidth

**Describe the solution you'd like**
The initial problem that I found is the below code  snippet [of this [file](https://github.com/CircuitVerse/mobile-app/blob/master/lib/ui/views/ib/ib_page_view.dart#L81)]
![image](https://user-images.githubusercontent.com/57363826/208684863-e51bb4e8-8e5c-4761-ba6e-ab489073dd98.png)
It every time rebuild UI, but actually, a full-screen rebuild is not required, the buttons themselves need to be only rebuilt. with setState, we can not achieve that.
Do, We need to convert the state updates logic from setState to Provider. 

**Are you working on this? (Yes/No)**
Yes

**Comment by Tanmoy741127** [comment]
@manjotsidhu can you verify the issue and assign this .

**Comment by Tanmoy741127** [comment]
@manjotsidhu can you verify the issue ?

**Comment by Tanmoy741127** [comment]
@manjotsidhu can you pls take a look.

**Comment by Tanmoy741127** [comment]
@manjotsidhu @aman-singh7 can you pls take a look !

**Comment by manjotsidhu** [comment]
@Tanmoy741127 Please go ahead and work on this issue

**Comment by Tanmoy741127** [comment]
@manjotsidhu thanks !
