### ISSUE TITLE
Revamp the `Feature circuits page`

### ISSUE THREAD

**Issue by Tanmoy741127** [CircuitVerse/mobile-app#269]
**Is your feature request related to a problem? Please describe.**
Make UI interaction smoother.
1. If the network speed little bit slow, the loading time of circuits in `Featured Circuits` page varies and feels like unresponsive. 
2. We need to press `Load more` button again and again .

| 1. Blank screen while loading | 2, Load more button |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/57363826/221574085-6b2ad7a9-8017-42df-b964-f3f623e12fc3.jpeg" width="250px" /> | <img src="https://user-images.githubusercontent.com/57363826/221574096-5fa0e68c-8306-4eb2-a6bb-4549b23351e3.jpeg" width="250px" /> |
| --- | --- |

**Describe the solution you'd like**
1. Show a loading spinner in screen while loading the circuits
2. Replace `Load More` button with Infinite Scrolling. As soon as the user come at end of list, next list will start loading.

**Are you working on this? (Yes/No)**
No

**Comment by danger-ahead** [comment]
Kindly assign me the issue.
