### ISSUE TITLE
Error in Heading Tag(Toolbox) of Add Assigment page.

### ISSUE THREAD

**Issue by shagun25** [CircuitVerse/mobile-app#28]
![ToolBox](https://user-images.githubusercontent.com/63994999/100536332-efaa9c00-3245-11eb-977e-4783b00ba25d.jpeg)
size constraints need to be there.
Are you working on it? Yes

**Comment by manjotsidhu** [comment]
Actually its part of `html_editor` package which uses [summernote](https://summernote.org/). The current library is not stable and hence we might require a custom implementation of a better WYSIWYG editor.

**Comment by shagun25** [comment]
> Actually its part of `html_editor` package which uses [summernote](https://summernote.org/). The current library is not stable and hence we might require a custom implementation of a better WYSIWYG editor.

I too checked the same issue, currently finding out the solution to modify the editor.

**Comment by manjotsidhu** [comment]
> Actually its part of `html_editor` package which uses [summernote](https://summernote.org/). The current library is not stable and hence we might require a custom implementation of a better WYSIWYG editor.

I just found that this might be good for our use instead of using WebView based libraries for WYSIWYG editor.
https://levelup.gitconnected.com/flutter-medium-like-text-editor-b41157f50f0e
