### ISSUE TITLE
Issue in adding group members

### ISSUE THREAD

**Issue by shagun25** [CircuitVerse/mobile-app#29]
![pending](https://user-images.githubusercontent.com/63994999/100537043-1b7c5080-324b-11eb-9be6-87205aa2cc43.jpeg)
If the previously entered email has not accepted the invitation to signup 
then we are not able to add new user's email address in it 
as it shows pending.
**Solution**: codebase need to made in such a way that even if previous user not accepted the invitation, still it should add new user.
Are you working on it? Yes

**Comment by manjotsidhu** [comment]
@shagun25 I think this is not an issue, pending message is for all users when invite has been sent successfully. I tried reproducing the issue but it's working even if previous user has not accepted/rejected the invite.
