### ISSUE TITLE
[Feature]Usage of Focus Nodes

### ISSUE THREAD

**Issue by jaggu21** [CircuitVerse/mobile-app#31]
**Is your feature request related to a problem? Please describe.**
Currently all the forms in the app do not use focus nodes which means user will have to always select on the next input field manually. Providing an option to navigate to next input field from the keyboard will look great!

**Solution**
Usage of focus nodes.

**Are you working on this?**
Yes.

**Comment by jaggu21** [comment]
@tachyons and @Nitish145 please let me know your thoughts on this. I have already made changes accordingly. Let me know if I should make a PR.

**Comment by Nitish145** [comment]
@jaggu21 this would be a good addition. Please raise a PR.
