### ISSUE TITLE
Profile Name change is not reflected on App Drawer

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/mobile-app#33]
### Issue
After changing Profile Name, the new name is not reflecting in App Drawer and it will show new name only after restarting the App.

### Steps to reproduce this issue -
1. Go to Profile > Edit Profile > Change Name.
2. Check App Drawer, it should be reflecting the old name.
3. Restart the App and it will show the newly changed name.

Are you working on this? **No**

**Comment by cyber-venom003** [comment]
@manjotsidhu Can I work on this??

**Comment by manjotsidhu** [comment]
> @manjotsidhu Can I work on this??
> 

Sure 👍

**Comment by pkspyder007** [comment]
I am new to flutter but I managed to run the app locally. what I see is that we need some kind of state management to handle this change for e.g. using the Provider package to manage updates in the state.

Is there any other way of achieving this?

**Comment by manjotsidhu** [comment]
> I am new to flutter but I managed to run the app locally. what I see is that we need some kind of state management to handle this change for e.g. using the Provider package to manage updates in the state.
> 
> Is there any other way of achieving this?

In the App currently Provider package is used for state management.

**Comment by rj-since-2000** [comment]
is the issue resolved ?

**Comment by pkspyder007** [comment]
@rj-since-2000 Not yet, I tried but could not get it done.

**Comment by rj-since-2000** [comment]
> ### Issue
> After changing Profile Name, the new name is not reflecting in App Drawer and it will show new name only after restarting the App.
> 
> ### Steps to reproduce this issue -
> 1. Go to Profile > Edit Profile > Change Name.
> 2. Check App Drawer, it should be reflecting the old name.
> 3. Restart the App and it will show the newly changed name.
> 
> Are you working on this? **No**

@manjotsidhu Actually you don't need to restart the app to see the change in the username. Once I change the name and open the app drawer the name isn't updated yet but once I open(or click on) any other option in the app drawer the username is updated automatically in the app drawer.

**Comment by manjotsidhu** [comment]
> > ### Issue
> > After changing Profile Name, the new name is not reflecting in App Drawer and it will show new name only after restarting the App.
> > ### Steps to reproduce this issue -
> > 
> > 1. Go to Profile > Edit Profile > Change Name.
> > 2. Check App Drawer, it should be reflecting the old name.
> > 3. Restart the App and it will show the newly changed name.
> > 
> > Are you working on this? **No**
> 
> @manjotsidhu Actually you don't need to restart the app to see the change in the username. Once I change the name and open the app drawer the name isn't updated yet but once I open(or click on) any other option in the app drawer the username is updated automatically in the app drawer.

Yeah that also works, the basic issue is that the AppDrawer state is not changed as soon as the name is changed.

**Comment by rj-since-2000** [comment]
> > > ### Issue
> > > After changing Profile Name, the new name is not reflecting in App Drawer and it will show new name only after restarting the App.
> > > ### Steps to reproduce this issue -
> > > 
> > > 1. Go to Profile > Edit Profile > Change Name.
> > > 2. Check App Drawer, it should be reflecting the old name.
> > > 3. Restart the App and it will show the newly changed name.
> > > 
> > > Are you working on this? **No**
> > 
> > 
> > @manjotsidhu Actually you don't need to restart the app to see the change in the username. Once I change the name and open the app drawer the name isn't updated yet but once I open(or click on) any other option in the app drawer the username is updated automatically in the app drawer.
> 
> Yeah that also works, the basic issue is that the AppDrawer state is not changed as soon as the name is changed.

This is because the drawer state is changing only when a drawer option is clicked on!
I have solved the issue using MultiProvider considering minimalistic changes in the code design. Should I create a PR @manjotsidhu ?

**Comment by manjotsidhu** [comment]
AppDrawer state is managed by Provider package, I think you can use that to update the state when name is changed.

**Comment by sidB67** [comment]
is this issue resolved? If not can it be assigned to me?

**Comment by aman-singh7** [comment]
@manjotsidhu can I work on this?
