### ISSUE TITLE
add a splash screen

### ISSUE THREAD

**Issue by guptapriyanshu7** [CircuitVerse/mobile-app#51]
When the app boots it shows a blank white screen, i will add a CircuitVerse splash icon.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add drawables.

**Additional context**

- Previously

![cv_prev](https://user-images.githubusercontent.com/60141300/104229238-001f7a80-5472-11eb-941a-c68bd6812f18.jpg)

- Now

![cv_now](https://user-images.githubusercontent.com/60141300/104229263-0a417900-5472-11eb-93e9-ed6e4145530c.jpg)

**Are you working on this? (Yes/No)**
Yes

**Comment by manjotsidhu** [comment]
@guptapriyanshu7 are you sure you are not able to see the splash screen ? There is already a splash screen in the app

**Comment by guptapriyanshu7** [comment]
@manjotsidhu , yeah actually there is a landing icon i have seen , but before that for like 1-2 seconds there is a blank screen

**Comment by manjotsidhu** [comment]
@guptapriyanshu7 The current landing page is the splash screen and that 1-2 seconds blank screen occurs only on debug build I think.

**Comment by manjotsidhu** [comment]
Here is how the release build looks like :

https://user-images.githubusercontent.com/22657113/104269822-2e767780-54bd-11eb-8160-61632be05e73.mp4

**Comment by guptapriyanshu7** [comment]
@manjotsidhu ,okay so in release that screen comes for a split second.

**Comment by manjotsidhu** [comment]
Actually that is not even a screen, its just a delay in loading the Splash Screen. How would you remove that delay ?

**Comment by guptapriyanshu7** [comment]
Actually the current implementation is different
Here's what i see

https://user-images.githubusercontent.com/60141300/104271414-e0fc0980-54c0-11eb-84d1-724cfc81fcfb.mp4

**Comment by manjotsidhu** [comment]
> Actually the current implementation is different
> Here's what i see
> 
> The icon you have added or it is already there ?

**Comment by guptapriyanshu7** [comment]
@manjotsidhu No no, I have added.

**Comment by manjotsidhu** [comment]
Ok, you can make PR.
