### ISSUE TITLE
Add pinch to zoom in all the circuit image. Some images are very small and viewing the text is difficult without zooming it.

### ISSUE THREAD

**Issue by pratikbaid3** [CircuitVerse/mobile-app#56]
**Is your feature request related to a problem? Please describe.**
The circuit displayed in the project detail page is very small and there is no option to zoom.

**Describe the solution you'd like**
Add a full screen icon with the image that redirects the user to another page with the full screen of the image, this view would allow pinch to zoom so that the user can easily zoom and view the entire circuit

**Describe alternatives you've considered**
Alternatively, I could add a pinch to zoom in the existing page that allows to expand the image.

**Additional context**
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-16 at 00 16 59](https://user-images.githubusercontent.com/52864956/104766355-6b2dc180-5790-11eb-8b79-9ad299cfa57f.png)

**Are you working on this? (Yes/No)**
Yes

**Comment by NishantChandla** [comment]
Can I work on this? Can I add a full-screen view with pinch zoom on the image click?

**Comment by pratikbaid3** [comment]
Hi @NishantChandla I have already started working on this and will be creating a PR in the coming days. Thanks

**Comment by NishantChandla** [comment]
Okay!
