### ISSUE TITLE
Display rating of circuits in more better way

### ISSUE THREAD

**Issue by spiderxm** [CircuitVerse/mobile-app#60]
## Rating show one star only when the rating is 1 stars or 5 stars.
![WhatsApp Image 2021-01-23 at 8 15 02 PM](https://user-images.githubusercontent.com/53966291/105590349-0be73700-5db8-11eb-9a27-956df6541515.jpeg)
![WhatsApp Image 2021-01-23 at 8 15 04 PM](https://user-images.githubusercontent.com/53966291/105590780-2ae5c900-5db8-11eb-8c16-967ef6cc9989.jpeg)
### I will work on this.

**Comment by Nitish145** [comment]
Here stars don't mean rating, rather it is the number of people who starred this project. Closing this
