### ISSUE TITLE
Add a text message if no circuits or favourites are present.

### ISSUE THREAD

**Issue by spiderxm** [CircuitVerse/mobile-app#63]
If there are no circuits or favourite circuits blank area is shown.
A text message with some basic info should be there.

**Comment by spiderxm** [comment]
Assign me this issue

**Comment by Nitish145** [comment]
Try to implement what's on the web. Also, you need to comment and get started if no one else has claimed it by then for you to work on any issue.

**Comment by spiderxm** [comment]
Why are we not following standard procedure of assigning the issue and then work on it.
I am working on this issue but now its all in vain.
I have commented too.

**Comment by manjotsidhu** [comment]
@dakshp07 This issue was already assigned to @spiderxm 2 days ago. You have to follow the community guidelines of contributing.

**Comment by spiderxm** [comment]
Thanks

**Comment by manjotsidhu** [comment]
@Nitish145 There are 2 PRs created by @dakshp07 and @spiderxm for this issue, #64 and #65. Kindly resolve the conflict between them.

**Comment by manjotsidhu** [comment]
@Nitish145 you can review and merge any one from #64 and #65
