### ISSUE TITLE
Adding a button on HomeScreen that directs the user to CircuitVerse website

### ISSUE THREAD

**Issue by CoderMayhem** [CircuitVerse/mobile-app#68]
**Is your feature request related to a problem? Please describe.**
The Home Screen of the app has no feature to get the user to the Circuit Verse website.

**Describe the solution you'd like**
My idea is to keep a button that directs the user to the Circuit Verse website.

**Additional context**

[Link to the demo video](https://drive.google.com/file/d/1ErrIaaBYbmMaIX9NrMUm2oH1wGcxQL3O/view?usp=sharing)

**Are you working on this? (Yes/No)**
Yes. Please tell me if I should go ahead with this.

**Comment by Nitish145** [comment]
You can go ahead with any issue if any other contributor does not claim the issue. In this case, it's a yes!
