### ISSUE TITLE
Showing starred in unstarred project

### ISSUE THREAD

**Issue by iCoder-007** [CircuitVerse/mobile-app#70]
When one goes from favourites to project detail and unstar the already starred project and pops back to favourites and once again goes project detail page the star button shows it as starred.

Have a look

https://user-images.githubusercontent.com/55887676/107152066-eea39280-698b-11eb-98a2-1811d2065447.mp4

**Comment by manjotsidhu** [comment]
That's because the state of favourites circuit doesn't reload when this happens

**Comment by devansh12b2** [comment]
I want to work on this issue; please assign it to me.

**Comment by aman-singh7** [comment]
Hey @manjotsidhu, can I work on this?

**Comment by ItsAdityaKSingh** [comment]
@aman-singh7 Hey Aman! Currently I am working on resolving this issue. If not resolved, you may see it through :)

**Comment by aman-singh7** [comment]
@ItsAdityaKSingh Please do mention before starting to work on the issue.

**Comment by ItsAdityaKSingh** [comment]
@aman-singh7  I am currently trying to resolve it. Will let you know at the earliest!
