### ISSUE TITLE
Release app on firebase app distribution to get user feedback [develop CI]

### ISSUE THREAD

**Issue by ayan-biswas0412** [CircuitVerse/mobile-app#75]
**Is your feature request related to a problem? Please describe.**

It is not a problem but a usability enhancement to the project

**Describe the solution you'd like**
I was wondering that if a person is kind of non-developer or haven't been to GitHub then we can provide them the apk via firebase app distribution and they can test the app and developers can get the comments from the users via a good way.
Writing a GitHub actions which will directly push the app to firebase app distribution and beta testers  will get email from app distribution about our new pre release version automatically.

**Describe alternatives you've considered**
Alternatives are already there to release the app via an apk which is available in GitHub artefact.

**Additional context**
You can read about firebase app distribution here https://firebase.google.com/products/app-distribution

**Are you working on this? (Yes/No)**
I can work on this issue if other mentors of this projects agrees with this.

**Comment by manjotsidhu** [comment]
We currently don't have a set of testers in mobile-app and since its not released on App Stores, I don't think pre-release would be beneficial.

Tagging mentors - @Nitish145 @tachyons

**Comment by Nitish145** [comment]
We will soon be releasing on playstore. And if some non-developer wanted to test the app, we would require his/her email, that's kind of a hassle imo. So, playstore/appstore would anyday be a good option.

**Comment by ayan-biswas0412** [comment]
> We will soon be releasing on playstore. And if some non-developer wanted to test the app, we would require his/her email, that's kind of a hassle imo. So, playstore/appstore would anyday be a good option.

just a suggestion : I thought to keep a form in the main website to collect the emails and directly add them as testers in app distribution via api call

**Comment by tachyons** [comment]
We can afford to pay for a google play account, that is not an issue. Only iOS is an issue as app store is very expensive

**Comment by ayan-biswas0412** [comment]
> We can afford to pay for a google play account, that is not an issue. Only iOS is an issue as app store is very expensive

for that we can also use this : https://firebase.google.com/docs/app-distribution/ios/distribute-console

**Comment by pratikbaid3** [comment]
@ayan-biswas0412 I don't think you can distribute a ios build through any channel without a apple developer account which costs $90/year.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 I don't think you can distribute a ios build through any channel without a apple developer account which costs $90/year.

I have seen this video and thought the similar thing : https://youtu.be/VbKiIJuGygg (please ignore the language in the video, not available in English 😅)

**Comment by kishanhitk** [comment]
I just read the docs from firebase and in [Step 3](https://firebase.google.com/docs/app-distribution/ios/distribute-console#register-tester-devices) they have mentioned that you need an Apple Developer Account to add a test device.

**Comment by ayan-biswas0412** [comment]
> I just read the docs from firebase and in [Step 3](https://firebase.google.com/docs/app-distribution/ios/distribute-console#register-tester-devices) they have mentioned that you need an Apple Developer Account to add a test device.

sorry my bad I missed the info 😢
