### ISSUE TITLE
Updating the profile with name less than tree characters

### ISSUE THREAD

**Issue by OnyemaAnthony** [CircuitVerse/mobile-app#78]
A user can update his or her profile with one single character, the application only check for when the input for is empty, can I work on this
![Screenshot_20210314-095300](https://user-images.githubusercontent.com/50530242/111062949-634a7f00-84ac-11eb-9312-c42a1ad29813.png)

**Comment by OnyemaAnthony** [comment]
@manjotsidhu please can I work on this?

**Comment by tachyons** [comment]
There are many names with just two alphabets, So it is better to avoid judgement and avoid validation on name length
