### ISSUE TITLE
Validate password form

### ISSUE THREAD

**Issue by OnyemaAnthony** [CircuitVerse/mobile-app#79]
Right now in the password Field for the login and sign up form the user can try to login with or sign up with a single character password, I want to validate the frontend so that the user can only login or sign up with password greater than or equal to 6 characters

**Comment by OnyemaAnthony** [comment]
@manjotsidhu can I work on this?

**Comment by suyash-patil** [comment]
@manjotsidhu can we implement this with 8 characters?

**Comment by manjotsidhu** [comment]
@Nitish145 can you give your comments on do we need this "feature" ?

**Comment by Aadeesh11** [comment]
Is this issue open? I want to work on this.
