### ISSUE TITLE
CI/CD for Google Play Store using Fastlane

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/mobile-app#81]
Continuous Integration and Deployment of Mobile App should happen using Fastlane with the help of GitHub Actions. 
Changes pushed to `master` branch should automatically trigger GitHub Actions pipeline and Incremental build should automatically be deployed to Google Play Store.

**Comment by manjotsidhu** [comment]
@tachyons @Nitish145 Need your opinions on which platform we should deploy, GitHub Actions or Circle CI ?

**Comment by tachyons** [comment]
Can use github actions as we are already using it for CI

**Comment by manjotsidhu** [comment]
@Nitish145 @satu0king any updates about the Fastlane deployment variables being set in GitHub Actions ?

**Comment by Nitish145** [comment]
Will push the deployment action soon. Thanks for your PR :) @manjotsidhu
