### ISSUE TITLE
Toggle Full screen for Project Details view

### ISSUE THREAD

**Issue by abstrekt** [CircuitVerse/mobile-app#83]
**Is your feature request related to a problem? Please describe.**
Better view of the circuits.

**Describe the solution you'd like**
I think it be better to have a button to toggle the current circuit image in `Project Details` view as full screen instead of just able to zoom inside the fixed 1x1 widget.

**Are you working on this? (Yes/No)**
No

**Comment by jassi-singh** [comment]
hi, I want to work on this issue can I go ahead?

**Comment by manjotsidhu** [comment]
> hi, I want to work on this issue can I go ahead?

Sure go ahead!
