### ISSUE TITLE
Restrictions on number of characters to be used in form input fields

### ISSUE THREAD

**Issue by pavanjoshi914** [CircuitVerse/mobile-app#85]
**Is your feature request related to a problem? Please describe.**
     Mobile-app posess forms for  group creation , assignment creation , profile edits etc
     Currently majority of the input field of forms don't provide restrictions on number of characters to be used and results into uncleaner UI experience
      
**Describe the solution you'd like**
1> provide restriction on number of characters entered by user before submitting
2> Truncate strings so that limited number of characters are shown in UI 

**Additional context**
![Screenshot_20210403_130046](https://user-images.githubusercontent.com/55848322/113478208-0176a700-94a5-11eb-8f3d-68590b3d7053.jpg)

**Are you working on this? (Yes/No)**
No

**Comment by tachyons** [comment]
I don't think this add much value as it is up to the user to select the title, also text length restriction can be tricky for non English languages as many languages require more than one character to form an alphabet

**Comment by Anshnrag02** [comment]
May I work on it?
