### ISSUE TITLE
Timing spelling is wrong in front page

### ISSUE THREAD

**Issue by nrj-kr** [CircuitVerse/mobile-app#86]
**Describe the bug**
In the front page ,as the app opens the main screen after the logo, there is spelling mistake in timing. It is written "plot timimg diagrams" instead of "plot timing diagrams".
**To Reproduce**

1. Go to 'circuitverse app'
2. Scroll  to 'front page'
3. See error

**Expected behavior**
It should be written plot timing diagrams.

**Screenshots**

**Device Information [optional]:**

- OS: [Android]

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by Anshnrag02** [comment]
Kindly assign me this

**Comment by nrj-kr** [comment]
You can directly start working on the issue

**Comment by manjotsidhu** [comment]
A Pull Request has already been submitted, you can work on other issues.

**Comment by manjotsidhu** [comment]
Issue fixed by #90
