### ISSUE TITLE
Usage of relative paths instead of package paths. 

### ISSUE THREAD

**Issue by jaggu21** [CircuitVerse/mobile-app#9]
**Is your feature request related to a problem? Please describe.**

All the imports of lib folder are imported using packages.The official documentation recommends to use alternative paths instead.Although this is debatable topic,since the documentation has mentioned to use relative paths , I would suggest you to have a look into this issue. 

**Links**
 [Documentation](https://dart.dev/guides/language/effective-dart/usage#do-use-relative-paths-when-importing-libraries-within-your-own-packages-lib-directory)

**Are you working on this?**
Require approval before I can start working.

**Comment by Nitish145** [comment]
@jaggu21 we are following `pedantic` style recommendations which recommends [avoid_relative_lib_imports
](https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html).

**Comment by jaggu21** [comment]
> @jaggu21 we are following `pedantic` style recommendations which recommends [avoid_relative_lib_imports ](https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html)

Hey,Different resources support different arguments.There are contrasting answers by the Dart Team itself!
Thanks for clarifying!
