### ISSUE TITLE
Change in Icon Style

### ISSUE THREAD

**Issue by Anshnrag02** [CircuitVerse/mobile-app#91]
The app icon is in square shape not circular. This makes the app aesthetically unappealing and it is not in sync with material design concepts and gives an asymmetric look in comparison to other apps. 

Kindly change the app icon to a circular shape.

![WhatsApp Image 2021-05-20 at 12 49 53 PM](https://user-images.githubusercontent.com/75090766/118938345-2b5c2e00-b96c-11eb-888a-11975a12d040.jpeg)

Kindly make the changes.

**Comment by manjotsidhu** [comment]
For me the App Icon is a little different but we need padding as well.
![Screenshot_2021-05-20-13-53-04-988_com.miui.home.jpg](https://user-images.githubusercontent.com/22657113/118945221-e4be0200-b972-11eb-88a1-753ffe27f683.jpg)

**Comment by Anshnrag02** [comment]
Totally agreed @manjotsidhu

**Comment by Anshnrag02** [comment]
Can you assign it to me?

**Comment by manjotsidhu** [comment]
> Can you assign it to me?

Sure go ahead 👍

**Comment by Anshnrag02** [comment]
Please check the PR.

**Comment by suyash-patil** [comment]
#96
