### ISSUE TITLE
Register Tile along with Login in Sidebar

### ISSUE THREAD

**Issue by suyash-patil** [CircuitVerse/mobile-app#92]
**Is your feature request related to a problem? Please describe.**
Currently, there is only Login button in sidebar. If a user wants to register, he has to go to login page and then to signup page. After this feature, he can directly go to registration page.

**Describe the solution you'd like**
We can create a Register button so that user can go to register page directly.

**Are you working on this? (Yes/No)**
Yes, I am working on this issue.

**Comment by Nitish145** [comment]
This is not a useful feature imo, register option is only there in LogIn View (check [circuitverse.org](https://circuitverse.org)). Hence, closing!

**Comment by suyash-patil** [comment]
okay
