### ISSUE TITLE
Multiple Splash Screen 

### ISSUE THREAD

**Issue by Anshnrag02** [CircuitVerse/mobile-app#95]
Multiple Splash Screens are being observed

![WhatsApp Image 2021-05-22 at 11 52 38 AM](https://user-images.githubusercontent.com/75090766/119217556-989cca00-baf8-11eb-97dc-f8a9dddd8eea.jpeg)
![WhatsApp Image 2021-05-22 at 11 52 38 AM (1)](https://user-images.githubusercontent.com/75090766/119217557-99cdf700-baf8-11eb-87f8-34ca5a091d2d.jpeg)

multiple splash screens are not required.

**Comment by manjotsidhu** [comment]
This is not an Issue but actually is part of running any android app. The first Splash screen is visible while the Flutter is about to run the Main dart And then the second Splash screen is when our authentication happens.

**Comment by Anshnrag02** [comment]
Can we have similar-looking splash in both cases?
For a user it will look like 2 screens otherwise

**Comment by manjotsidhu** [comment]
Hmmm you can but it's not a big deal, the first splash screen surely takes <1 sec.
