### ISSUE TITLE
Dart: Migrate to null safety

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/mobile-app#99]
**Describe the bug**
We should be migrating to null safety which was introduced in Dart 2.0. But before that, we need to make sure that first our dependencies are migrated to null safety according to this Guide: https://dart.dev/null-safety/migration-guide

```
Wait for the packages that you depend on to migrate.
Migrate your package’s code, preferably using the interactive migration tool.
Statically analyze your package’s code.
Test to make sure your changes work.
If the package is already on pub.dev, publish the null-safe version as a prerelease version.
```

This Issue serves as a checklist of all the packages which have been migrated to null safety. 

- [x] animations
- [x] cupertino_icons
- [x] datetime_picker_formfield
- [x] flutter_facebook_auth
- [x] flutter_html
- [x] #119
- [x] flutter_keyboard_visibility
- [x] flutter_summernote (published on 21st June)
- [x] flutter_svg
- [x] flutter_typeahead
- [x] get
- [x] get_it
- [x] google_sign_in
- [x] html
- [x] http
- [x] intl
- [x] mockito
- [x] oauth2_client
- [x] photo_view
- [x] provider
- [x] share
- [x] shared_preferences
- [x] theme_provider
- [x] timeago
- [x] transparent_image
- [x] url_launcher

Once this list is complete which means all our packages are sound null safety. We should use migration tool to migrate to null safety.

**Comment by manjotsidhu** [comment]
@Nitish145 `flutter_icons` is not maintained anymore, can we switch to `fluttericon`:https://pub.dev/packages/fluttericon ?

**Comment by Nitish145** [comment]
Go Ahead @manjotsidhu

**Comment by manjotsidhu** [comment]
> @Nitish145 `flutter_icons` is not maintained anymore, can we switch to `fluttericon`:https://pub.dev/packages/fluttericon ?

@ShreyaPrasad1209 this can also be considered as #good-first-issue.

**Comment by Mobasherah12** [comment]
@manjotsidhu @ShreyaPrasad1209 Hi, I'm an Open Source Day participant, willing to work on this. Please do assign me.

**Comment by manjotsidhu** [comment]
> @manjotsidhu @ShreyaPrasad1209 Hi, I'm an Open Source Day participant, willing to work on this. Please do assign me.

Go ahead!

**Comment by prasadsunny1** [comment]
What more needs to be done in this issue?

**Comment by manjotsidhu** [comment]
> What more needs to be done in this issue?

https://dart.dev/null-safety/migration-guide

**Comment by prasadsunny1** [comment]
Let me try migrating

**Comment by aman-singh7** [comment]
@manjotsidhu can I work on this?

**Comment by dipanshparmar** [comment]
Hey @manjotsidhu, may I take this up?
